# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/embedding.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/embedding.proto\x12\x07test.v1\"2\n\x1bGetRelatedEmbeddingsRequest\x12\x13\n\x0bwebsite_ids\x18\x01 \x03(\t\"3\n\x1cGetRelatedEmbeddingsResponse\x12\x13\n\x0bwebsite_ids\x18\x02 \x03(\t\"!\n\x1fQueueEmbeddingGenerationRequest\"\"\n QueueEmbeddingGenerationResponse2\xe8\x01\n\x10\x45mbeddingService\x12\x63\n\x14GetRelatedEmbeddings\x12$.test.v1.GetRelatedEmbeddingsRequest\x1a%.test.v1.GetRelatedEmbeddingsResponse\x12o\n\x18QueueEmbeddingGeneration\x12(.test.v1.QueueEmbeddingGenerationRequest\x1a).test.v1.QueueEmbeddingGenerationResponseB1Z/github.com/lassenordahl/mall/server/proto;protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.embedding_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/github.com/lassenordahl/mall/server/proto;proto'
  _GETRELATEDEMBEDDINGSREQUEST._serialized_start=34
  _GETRELATEDEMBEDDINGSREQUEST._serialized_end=84
  _GETRELATEDEMBEDDINGSRESPONSE._serialized_start=86
  _GETRELATEDEMBEDDINGSRESPONSE._serialized_end=137
  _QUEUEEMBEDDINGGENERATIONREQUEST._serialized_start=139
  _QUEUEEMBEDDINGGENERATIONREQUEST._serialized_end=172
  _QUEUEEMBEDDINGGENERATIONRESPONSE._serialized_start=174
  _QUEUEEMBEDDINGGENERATIONRESPONSE._serialized_end=208
  _EMBEDDINGSERVICE._serialized_start=211
  _EMBEDDINGSERVICE._serialized_end=443
# @@protoc_insertion_point(module_scope)
