// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: proto/embedding.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRelatedEmbeddingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WebsiteIds    []string               `protobuf:"bytes,1,rep,name=website_ids,json=websiteIds,proto3" json:"website_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelatedEmbeddingsRequest) Reset() {
	*x = GetRelatedEmbeddingsRequest{}
	mi := &file_proto_embedding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelatedEmbeddingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelatedEmbeddingsRequest) ProtoMessage() {}

func (x *GetRelatedEmbeddingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_embedding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelatedEmbeddingsRequest.ProtoReflect.Descriptor instead.
func (*GetRelatedEmbeddingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_embedding_proto_rawDescGZIP(), []int{0}
}

func (x *GetRelatedEmbeddingsRequest) GetWebsiteIds() []string {
	if x != nil {
		return x.WebsiteIds
	}
	return nil
}

type GetRelatedEmbeddingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WebsiteIds    []string               `protobuf:"bytes,2,rep,name=website_ids,json=websiteIds,proto3" json:"website_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelatedEmbeddingsResponse) Reset() {
	*x = GetRelatedEmbeddingsResponse{}
	mi := &file_proto_embedding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelatedEmbeddingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelatedEmbeddingsResponse) ProtoMessage() {}

func (x *GetRelatedEmbeddingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_embedding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelatedEmbeddingsResponse.ProtoReflect.Descriptor instead.
func (*GetRelatedEmbeddingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_embedding_proto_rawDescGZIP(), []int{1}
}

func (x *GetRelatedEmbeddingsResponse) GetWebsiteIds() []string {
	if x != nil {
		return x.WebsiteIds
	}
	return nil
}

type QueueEmbeddingGenerationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueEmbeddingGenerationRequest) Reset() {
	*x = QueueEmbeddingGenerationRequest{}
	mi := &file_proto_embedding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueEmbeddingGenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueEmbeddingGenerationRequest) ProtoMessage() {}

func (x *QueueEmbeddingGenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_embedding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueEmbeddingGenerationRequest.ProtoReflect.Descriptor instead.
func (*QueueEmbeddingGenerationRequest) Descriptor() ([]byte, []int) {
	return file_proto_embedding_proto_rawDescGZIP(), []int{2}
}

type QueueEmbeddingGenerationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueEmbeddingGenerationResponse) Reset() {
	*x = QueueEmbeddingGenerationResponse{}
	mi := &file_proto_embedding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueEmbeddingGenerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueEmbeddingGenerationResponse) ProtoMessage() {}

func (x *QueueEmbeddingGenerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_embedding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueEmbeddingGenerationResponse.ProtoReflect.Descriptor instead.
func (*QueueEmbeddingGenerationResponse) Descriptor() ([]byte, []int) {
	return file_proto_embedding_proto_rawDescGZIP(), []int{3}
}

var File_proto_embedding_proto protoreflect.FileDescriptor

var file_proto_embedding_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x76, 0x31,
	0x22, 0x3e, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x45, 0x6d,
	0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x73,
	0x22, 0x3f, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x45, 0x6d,
	0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x49, 0x64,
	0x73, 0x22, 0x21, 0x0a, 0x1f, 0x51, 0x75, 0x65, 0x75, 0x65, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64,
	0x69, 0x6e, 0x67, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x22, 0x0a, 0x20, 0x51, 0x75, 0x65, 0x75, 0x65, 0x45, 0x6d, 0x62,
	0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xe8, 0x01, 0x0a, 0x10, 0x45, 0x6d, 0x62,
	0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x63, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x45, 0x6d, 0x62, 0x65, 0x64,
	0x64, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x24, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64,
	0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64,
	0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x6f, 0x0a, 0x18, 0x51, 0x75, 0x65, 0x75, 0x65, 0x45, 0x6d, 0x62, 0x65, 0x64,
	0x64, 0x69, 0x6e, 0x67, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x45, 0x6d,
	0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e,
	0x67, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x6f, 0x72, 0x64, 0x61, 0x68, 0x6c, 0x2f, 0x6d,
	0x61, 0x6c, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_embedding_proto_rawDescOnce sync.Once
	file_proto_embedding_proto_rawDescData = file_proto_embedding_proto_rawDesc
)

func file_proto_embedding_proto_rawDescGZIP() []byte {
	file_proto_embedding_proto_rawDescOnce.Do(func() {
		file_proto_embedding_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_embedding_proto_rawDescData)
	})
	return file_proto_embedding_proto_rawDescData
}

var file_proto_embedding_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_embedding_proto_goTypes = []any{
	(*GetRelatedEmbeddingsRequest)(nil),      // 0: test.v1.GetRelatedEmbeddingsRequest
	(*GetRelatedEmbeddingsResponse)(nil),     // 1: test.v1.GetRelatedEmbeddingsResponse
	(*QueueEmbeddingGenerationRequest)(nil),  // 2: test.v1.QueueEmbeddingGenerationRequest
	(*QueueEmbeddingGenerationResponse)(nil), // 3: test.v1.QueueEmbeddingGenerationResponse
}
var file_proto_embedding_proto_depIdxs = []int32{
	0, // 0: test.v1.EmbeddingService.GetRelatedEmbeddings:input_type -> test.v1.GetRelatedEmbeddingsRequest
	2, // 1: test.v1.EmbeddingService.QueueEmbeddingGeneration:input_type -> test.v1.QueueEmbeddingGenerationRequest
	1, // 2: test.v1.EmbeddingService.GetRelatedEmbeddings:output_type -> test.v1.GetRelatedEmbeddingsResponse
	3, // 3: test.v1.EmbeddingService.QueueEmbeddingGeneration:output_type -> test.v1.QueueEmbeddingGenerationResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_embedding_proto_init() }
func file_proto_embedding_proto_init() {
	if File_proto_embedding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_embedding_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_embedding_proto_goTypes,
		DependencyIndexes: file_proto_embedding_proto_depIdxs,
		MessageInfos:      file_proto_embedding_proto_msgTypes,
	}.Build()
	File_proto_embedding_proto = out.File
	file_proto_embedding_proto_rawDesc = nil
	file_proto_embedding_proto_goTypes = nil
	file_proto_embedding_proto_depIdxs = nil
}
