# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import api_pb2 as api__pb2


class TestServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendPing = channel.unary_unary(
                '/test.v1.TestService/SendPing',
                request_serializer=api__pb2.PingRequest.SerializeToString,
                response_deserializer=api__pb2.PingResponse.FromString,
                )


class TestServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendPing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendPing': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPing,
                    request_deserializer=api__pb2.PingRequest.FromString,
                    response_serializer=api__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'test.v1.TestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TestService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendPing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/test.v1.TestService/SendPing',
            api__pb2.PingRequest.SerializeToString,
            api__pb2.PingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ConsoleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNewWebsites = channel.unary_unary(
                '/test.v1.ConsoleService/GetNewWebsites',
                request_serializer=api__pb2.GetWebsitesResponse.SerializeToString,
                response_deserializer=api__pb2.GetWebsitesResponse.FromString,
                )


class ConsoleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetNewWebsites(self, request, context):
        """GetNewWebsites returns a list of websites that fill in the remaining slots
        on the UI. It returns a unique list that contains zero of the websites that
        have already been generated on the map.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConsoleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNewWebsites': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNewWebsites,
                    request_deserializer=api__pb2.GetWebsitesResponse.FromString,
                    response_serializer=api__pb2.GetWebsitesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'test.v1.ConsoleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ConsoleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetNewWebsites(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/test.v1.ConsoleService/GetNewWebsites',
            api__pb2.GetWebsitesResponse.SerializeToString,
            api__pb2.GetWebsitesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
