# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import embedding_pb2 as proto_dot_embedding__pb2


class EmbeddingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRelatedEmbeddings = channel.unary_unary(
                '/test.v1.EmbeddingService/GetRelatedEmbeddings',
                request_serializer=proto_dot_embedding__pb2.GetRelatedEmbeddingsRequest.SerializeToString,
                response_deserializer=proto_dot_embedding__pb2.GetRelatedEmbeddingsResponse.FromString,
                )
        self.QueueEmbeddingGeneration = channel.unary_unary(
                '/test.v1.EmbeddingService/QueueEmbeddingGeneration',
                request_serializer=proto_dot_embedding__pb2.QueueEmbeddingGenerationRequest.SerializeToString,
                response_deserializer=proto_dot_embedding__pb2.QueueEmbeddingGenerationResponse.FromString,
                )


class EmbeddingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRelatedEmbeddings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueueEmbeddingGeneration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRelatedEmbeddings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRelatedEmbeddings,
                    request_deserializer=proto_dot_embedding__pb2.GetRelatedEmbeddingsRequest.FromString,
                    response_serializer=proto_dot_embedding__pb2.GetRelatedEmbeddingsResponse.SerializeToString,
            ),
            'QueueEmbeddingGeneration': grpc.unary_unary_rpc_method_handler(
                    servicer.QueueEmbeddingGeneration,
                    request_deserializer=proto_dot_embedding__pb2.QueueEmbeddingGenerationRequest.FromString,
                    response_serializer=proto_dot_embedding__pb2.QueueEmbeddingGenerationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'test.v1.EmbeddingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EmbeddingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRelatedEmbeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/test.v1.EmbeddingService/GetRelatedEmbeddings',
            proto_dot_embedding__pb2.GetRelatedEmbeddingsRequest.SerializeToString,
            proto_dot_embedding__pb2.GetRelatedEmbeddingsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueueEmbeddingGeneration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/test.v1.EmbeddingService/QueueEmbeddingGeneration',
            proto_dot_embedding__pb2.QueueEmbeddingGenerationRequest.SerializeToString,
            proto_dot_embedding__pb2.QueueEmbeddingGenerationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
